#!/usr/bin/env bash
# 04-register-service.sh — Register the launchd-supervised daemon (macOS).
#
# Generates two artifacts:
# 1. A wrapper script at <install-path>/launcher-wrapper.sh that sources
#    the env-file (since launchd has no native EnvironmentFile directive)
#    then execs the venv python with `-m recto launch <yaml>`.
# 2. A launchd plist at /Library/LaunchDaemons/<label>.plist pointing
#    at the wrapper script.
#
# Then runs `launchctl bootstrap` to load + enable the daemon. Daemon
# stays STOPPED after this script — 05-smoke-test.sh starts it.
#
# Usage:
#   sudo bash ./04-register-service.sh \
#       --service-name my-consumer \
#       --service-yaml /opt/recto-deploy/my-consumer.service.yaml \
#       --user _recto \
#       --group _recto
#
# Flags:
#   --service-name <name>   Service name. Used to compose launchd Label.
#   --service-yaml <path>   Absolute path to service.yaml.
#   --install-path <path>   Where Recto venv lives. Default: /usr/local/opt/recto.
#   --vault-root <path>     Where vaults live. Default: /usr/local/var/lib/recto.
#                           Env-file path is derived as <vault-root>/<service>/.env.
#   --user <name>           launchd UserName. Default: root.
#                           For least-privilege: create a _recto system user
#                           via dscl (see ../orchestrator-macos-deploy/README.md).
#   --group <name>          launchd GroupName. Default: matches --user (or wheel for root).
#   --label-prefix <prefix> launchd Label prefix. Default: "com.recto".
#                           Full Label = "<prefix>.<service-name>".
#   --description <text>    Optional description (no native launchd field;
#                           stored as a comment for operator-readability).
#
# Exit codes: 0 = success, 1 = failure

set -e

if [[ -t 1 ]]; then
    C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'
    C_CYAN=$'\033[36m'; C_DIM=$'\033[2m'; C_RESET=$'\033[0m'
else
    C_RED=""; C_GREEN=""; C_YELLOW=""; C_CYAN=""; C_DIM=""; C_RESET=""
fi

SERVICE_NAME=""
SERVICE_YAML=""
INSTALL_PATH="/usr/local/opt/recto"
VAULT_ROOT="/usr/local/var/lib/recto"
SVC_USER="root"
SVC_GROUP=""
LABEL_PREFIX="com.recto"
DESCRIPTION=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --service-name)    SERVICE_NAME="$2"; shift 2 ;;
        --service-yaml)    SERVICE_YAML="$2"; shift 2 ;;
        --install-path)    INSTALL_PATH="$2"; shift 2 ;;
        --vault-root)      VAULT_ROOT="$2"; shift 2 ;;
        --user)            SVC_USER="$2"; shift 2 ;;
        --group)           SVC_GROUP="$2"; shift 2 ;;
        --label-prefix)    LABEL_PREFIX="$2"; shift 2 ;;
        --description)     DESCRIPTION="$2"; shift 2 ;;
        -h|--help)         grep -E "^# " "$0" | sed 's/^# //'; exit 0 ;;
        *)                 echo "${C_RED}ERROR: unknown flag: $1${C_RESET}" >&2; exit 1 ;;
    esac
done

[[ -n "$SERVICE_NAME" ]] || { echo "${C_RED}ERROR: --service-name required${C_RESET}" >&2; exit 1; }
[[ -n "$SERVICE_YAML" ]] || { echo "${C_RED}ERROR: --service-yaml required${C_RESET}" >&2; exit 1; }

if [[ -z "$SVC_GROUP" ]]; then
    if [[ "$SVC_USER" == "root" ]]; then SVC_GROUP="wheel"; else SVC_GROUP="$SVC_USER"; fi
fi
[[ -z "$DESCRIPTION" ]] && DESCRIPTION="Recto-supervised service '$SERVICE_NAME'"

echo ""
echo "${C_CYAN}Recto orchestrator-macos-deploy — launchd daemon registration${C_RESET}"
echo "${C_CYAN}===============================================================${C_RESET}"
echo ""

# Validate
VENV_PYTHON="$INSTALL_PATH/.venv/bin/python"
[[ -x "$VENV_PYTHON" ]] || { echo "${C_RED}ERROR: venv not at $VENV_PYTHON. Run 02-create-venv.sh first.${C_RESET}" >&2; exit 1; }
[[ -f "$SERVICE_YAML" ]] || { echo "${C_RED}ERROR: ServiceYaml not at $SERVICE_YAML${C_RESET}" >&2; exit 1; }
if [[ "$SVC_USER" != "root" ]] && ! id -u "$SVC_USER" >/dev/null 2>&1; then
    echo "${C_RED}ERROR: --user '$SVC_USER' does not exist. See README.md for the dscl ceremony to create a _recto system user.${C_RESET}" >&2
    exit 1
fi

LABEL="${LABEL_PREFIX}.${SERVICE_NAME}"
PLIST_FILE="/Library/LaunchDaemons/${LABEL}.plist"
WRAPPER_PATH="$INSTALL_PATH/launcher-wrapper-${SERVICE_NAME}.sh"
ENV_FILE="$VAULT_ROOT/$SERVICE_NAME/.env"
LOG_DIR="/var/log/recto/$SERVICE_NAME"
mkdir -p "$LOG_DIR"
chown -R "$SVC_USER:$SVC_GROUP" "$LOG_DIR" 2>/dev/null || true

# Check whether daemon already loaded
IS_UPDATE="false"
if launchctl print "system/$LABEL" >/dev/null 2>&1; then
    IS_UPDATE="true"
    echo "${C_YELLOW}Daemon '$LABEL' already loaded; will bootout + re-bootstrap.${C_RESET}"
    launchctl bootout "system/$LABEL" || true
    sleep 1
fi

# Generate wrapper script that sources .env then execs the launcher
cat > "$WRAPPER_PATH" <<WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by Recto orchestrator-macos-deploy/04-register-service.sh
# Sources $ENV_FILE (if present) so launchd-managed env vars include
# every KEY=VALUE the operator manages there. Then execs the Recto launcher.
set -e
if [[ -r "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
fi
exec "$VENV_PYTHON" -m recto launch "$SERVICE_YAML"
WRAPPER_EOF
chmod 0755 "$WRAPPER_PATH"
chown "$SVC_USER:$SVC_GROUP" "$WRAPPER_PATH" 2>/dev/null || true
echo "${C_GREEN}Wrapper script: $WRAPPER_PATH${C_RESET}"

# Generate launchd plist
cat > "$PLIST_FILE" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- $DESCRIPTION
     Auto-generated by Recto orchestrator-macos-deploy/04-register-service.sh -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$WRAPPER_PATH</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$INSTALL_PATH</string>
    <key>UserName</key>
    <string>$SVC_USER</string>
    <key>GroupName</key>
    <string>$SVC_GROUP</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/stdout.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/stderr.log</string>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLIST_EOF
chmod 0644 "$PLIST_FILE"
chown root:wheel "$PLIST_FILE"
echo "${C_GREEN}Plist: $PLIST_FILE${C_RESET}"

# Bootstrap into launchd
echo "${C_CYAN}Running 'launchctl bootstrap system $PLIST_FILE'...${C_RESET}"
launchctl bootstrap system "$PLIST_FILE"
launchctl enable "system/$LABEL"

echo ""
echo "${C_CYAN}===============================================================${C_RESET}"
echo "${C_GREEN}Daemon:               $LABEL ($(if [[ "$IS_UPDATE" == "true" ]]; then echo 'updated'; else echo 'newly registered'; fi))${C_RESET}"
echo "${C_GREEN}Plist:                $PLIST_FILE${C_RESET}"
echo "${C_GREEN}Wrapper:              $WRAPPER_PATH${C_RESET}"
echo "${C_GREEN}User / Group:         $SVC_USER / $SVC_GROUP${C_RESET}"
echo "${C_GREEN}stdout log:           $LOG_DIR/stdout.log${C_RESET}"
echo "${C_GREEN}stderr log:           $LOG_DIR/stderr.log${C_RESET}"
echo "${C_GREEN}KeepAlive:            on-failure (restart unless clean exit)${C_RESET}"
echo ""
echo "${C_YELLOW}Daemon is registered but stopped. 05-smoke-test.sh starts it.${C_RESET}"
echo ""
echo "${C_CYAN}Next: sudo bash ./05-smoke-test.sh --service-name $SERVICE_NAME${C_RESET}"
echo ""
exit 0
