"""Helpers for `recto migrate-from-nssm`. Extracted from recto.cli.

These functions are pure (no I/O, no side effects) and small. They
live in their own module so cli.py stays under the Cowork Write-tool
size threshold while still being a thin dispatcher rather than a
1000-line god-module. Same pattern as ``recto._launcher_run`` --
private (underscore-prefix) module, re-imported by name from
``recto.cli``.

If you're reading this in v0.3+: feel free to inline these back into
cli.py once the Cowork sandbox is no longer the operator's primary
authoring environment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from recto.nssm import NssmConfig

__all__ = [
    "build_migration_plan",
    "escape_yaml",
    "generate_service_yaml",
    "partition_env_entries",
]


def partition_env_entries(
    entries: list[tuple[str, str]],
    *,
    keep_as_env: list[str] | None = None,
) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Split NSSM AppEnvironmentExtra entries into (secrets, plain_env).

    Operators pass ``--keep-as-env=NAME[,NAME...]`` on the
    ``migrate-from-nssm`` CLI to route specific keys into the
    generated YAML's ``spec.env:`` block instead of Credential
    Manager. The default (``keep_as_env=None`` or empty list) is
    conservative: every entry goes to CredMan, matching v0.1
    behavior. No surprise allow-list -- operators opt in
    per-migration.

    Returns ``(secrets, plain_env)``. Both lists preserve the input
    order.
    """
    keep_set = set(keep_as_env or ())
    secrets: list[tuple[str, str]] = []
    plain_env: list[tuple[str, str]] = []
    for k, v in entries:
        if k in keep_set:
            plain_env.append((k, v))
        else:
            secrets.append((k, v))
    return secrets, plain_env


def build_migration_plan(
    *,
    nssm_cfg: NssmConfig,
    secrets: list[tuple[str, str]],
    yaml_out: Path,
    python_exe: str,
    plain_env: list[tuple[str, str]] | None = None,
) -> dict[str, Any]:
    """Build a dict describing what migrate-from-nssm WOULD do.

    Secret VALUES are masked (replaced with '<redacted>') so the plan
    can be JSON-printed without leaking. Plain-env values (from
    ``--keep-as-env``) are NOT masked since they're explicitly
    operator-tagged as non-secret.
    """
    plain_env = plain_env or []
    return {
        "service": nssm_cfg.service,
        "current_app_path": nssm_cfg.app_path,
        "current_app_parameters": nssm_cfg.app_parameters,
        "current_app_directory": nssm_cfg.app_directory,
        "current_environment_extra_count": len(secrets) + len(plain_env),
        "secrets_to_install": [
            {"name": k, "value": "<redacted>"} for k, _ in secrets
        ],
        "plain_env_to_yaml": [
            {"name": k, "value": v} for k, v in plain_env
        ],
        "yaml_out": str(yaml_out),
        "new_app_path": python_exe,
        "new_app_parameters": f"-m recto launch {yaml_out}",
    }


def generate_service_yaml(
    *,
    service: str,
    nssm_cfg: NssmConfig,
    secret_keys: list[str],
    plain_env: list[tuple[str, str]] | None = None,
    secret_backend: str = "credman",
) -> str:
    """Produce the generated service.yaml text.

    Hand-rolled (not via PyYAML's dump) so we control formatting:
    fields appear in a stable order, comments are preserved, and the
    output is human-reviewable. PyYAML's default style would munge
    quoting on values with `:` or `#` and lose readability.

    ``plain_env`` (from ``--keep-as-env``) is rendered into the
    YAML's ``spec.env:`` block. ``secret_keys`` becomes the
    ``spec.secrets:`` block.
    """
    plain_env = plain_env or []
    lines: list[str] = []
    a = lines.append
    a("# Generated by `recto migrate-from-nssm`.")
    a(f"# Source NSSM service: {nssm_cfg.service}")
    a("# Review and edit before relying on this in production.")
    a("apiVersion: recto/v1")
    a("kind: Service")
    a("metadata:")
    a(f"  name: {service}")
    # Map NSSM's DisplayName -> YAML metadata.display_name (Papercut #3
    # additive field, v0.2.x+) and NSSM's Description -> YAML
    # metadata.description independently. Pre-Papercut-#3 behavior
    # collapsed NSSM DisplayName into a single YAML `description`
    # field, which on round-trip through `recto apply` then wrote the
    # same string back into both NSSM registry parameters -- lossy. New
    # migrations produce two distinct fields when both are set on the
    # source NSSM service. If only DisplayName is set, only display_name
    # is emitted (so `recto apply` won't pollute NSSM's Description from
    # "" to the DisplayName string on round-trip).
    if nssm_cfg.display_name:
        a(f"  display_name: \"{escape_yaml(nssm_cfg.display_name)}\"")
    if nssm_cfg.description:
        a(f"  description: \"{escape_yaml(nssm_cfg.description)}\"")
    a("spec:")
    a(f"  exec: \"{escape_yaml(nssm_cfg.app_path)}\"")
    if nssm_cfg.app_parameters:
        a("  args:")
        for w in nssm_cfg.app_parameters.split():
            a(f"    - \"{escape_yaml(w)}\"")
    if nssm_cfg.app_directory:
        a(f"  working_dir: \"{escape_yaml(nssm_cfg.app_directory)}\"")
    if secret_keys:
        a("  secrets:")
        for key in secret_keys:
            a(f"    - name: {key}")
            a(f"      source: {secret_backend}")
            a(f"      target_env: {key}")
            a("      required: true")
    if plain_env:
        a("  env:")
        for k, v in plain_env:
            a(f"    {k}: \"{escape_yaml(v)}\"")
    a("  restart:")
    a("    policy: always")
    a("    backoff: exponential")
    a("    initial_delay_seconds: 1")
    a("    max_delay_seconds: 60")
    a("    max_attempts: 10")
    a("")
    return "\n".join(lines)


def escape_yaml(s: str) -> str:
    """Escape backslashes and double-quotes for YAML double-quoted strings."""
    return s.replace("\\", "\\\\").replace("\"", "\\\"")
