using System;
using System.Formats.Asn1;
using System.Numerics;
using System.Security.Cryptography;
using Recto.Shared.Services;
using Xunit;

namespace Recto.Shared.Tests;

/// <summary>
/// Pins EcdsaSignatureFormat.DerToRaw against signatures generated by the
/// .NET runtime's own ECDSA implementation, plus a few hand-crafted edge-
/// case DER sequences (short components, components with the leading-0x00
/// positive-integer marker). The phone's iOS Secure Enclave + Android
/// keystore both emit DER ECDSA; the v0.4 wire protocol is raw R || S.
/// </summary>
public class EcdsaSignatureFormatTests
{
    [Fact]
    public void DerToRaw_ProducesExactly64Bytes_ForFreshlySignedMessage()
    {
        using var ecdsa = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var message = "hello recto"u8.ToArray();
        var derSig = ecdsa.SignData(message, HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence);

        var raw = EcdsaSignatureFormat.DerToRaw(derSig);

        Assert.Equal(64, raw.Length);
    }

    [Fact]
    public void DerToRaw_RoundTripsMatchesNetIeeeP1363Output()
    {
        // The .NET runtime can also emit raw R||S directly via the IEEE
        // P1363 format -- which is what JWS ES256 uses. Our DerToRaw should
        // produce the same bytes when given the DER form of the same
        // signature, signed with the same key over the same message.
        using var ecdsa = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var message = "round-trip test"u8.ToArray();

        var derSig = ecdsa.SignData(message, HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence);
        var p1363 = ecdsa.SignData(message, HashAlgorithmName.SHA256, DSASignatureFormat.IeeeP1363FixedFieldConcatenation);

        // Note: ECDSA is non-deterministic (the random k differs per call),
        // so derSig and p1363 here come from DIFFERENT signing operations
        // with different (r, s) pairs. We can't compare them directly.
        // Instead: convert derSig via our function, parse p1363 manually,
        // and verify both verify against the same public key. This proves
        // our DerToRaw produces a structurally-correct raw-R||S of the
        // SAME (r, s) we read from the DER input.
        var raw = EcdsaSignatureFormat.DerToRaw(derSig);

        // Re-encode raw back to DER and verify it round-trips through the
        // ECDSA verifier exactly like the original.
        var reDer = ReEncodeRawAsDer(raw);
        Assert.True(ecdsa.VerifyData(message, reDer, HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence));

        // Also verify p1363 (same shape, different signature) parses to 64.
        Assert.Equal(64, p1363.Length);
    }

    [Fact]
    public void DerToRaw_HandlesShortComponents_ZeroPadsLeft()
    {
        // Hand-crafted DER: SEQUENCE { INTEGER 0x01, INTEGER 0x02 }.
        // Both components are 1 byte; raw output should right-align them
        // into 32-byte slots (31 leading zeros + 1 byte each).
        var writer = new AsnWriter(AsnEncodingRules.DER);
        using (writer.PushSequence())
        {
            writer.WriteInteger(BigInteger.One);
            writer.WriteInteger(new BigInteger(2));
        }
        var der = writer.Encode();

        var raw = EcdsaSignatureFormat.DerToRaw(der);

        Assert.Equal(64, raw.Length);
        for (int i = 0; i < 31; i++) Assert.Equal(0, raw[i]);
        Assert.Equal(0x01, raw[31]);
        for (int i = 32; i < 63; i++) Assert.Equal(0, raw[i]);
        Assert.Equal(0x02, raw[63]);
    }

    [Fact]
    public void DerToRaw_StripsLeadingZeroPositiveMarker()
    {
        // DER encodes positive INTEGERs whose high bit would otherwise mark
        // them negative by prepending a 0x00 byte. For ECDSA P-256, that
        // yields a 33-byte component when r or s happens to have its high
        // bit set. Our parser must strip the leading zero and right-align
        // the remaining 32 bytes -- NOT keep the 33 bytes (would corrupt).
        // Build INTEGER { 0x00 0xFF 0x... }: the high-bit-set 32-byte value.
        var bigPositive = new byte[32];
        bigPositive[0] = 0xFF;
        for (int i = 1; i < 32; i++) bigPositive[i] = 0xAB;
        var bi = new BigInteger(bigPositive, isUnsigned: true, isBigEndian: true);

        var writer = new AsnWriter(AsnEncodingRules.DER);
        using (writer.PushSequence())
        {
            writer.WriteInteger(bi);
            writer.WriteInteger(BigInteger.One);
        }
        var der = writer.Encode();

        var raw = EcdsaSignatureFormat.DerToRaw(der);

        Assert.Equal(64, raw.Length);
        Assert.Equal(0xFF, raw[0]);
        for (int i = 1; i < 32; i++) Assert.Equal(0xAB, raw[i]);
        Assert.Equal(0x01, raw[63]);
    }

    [Fact]
    public void DerToRaw_RejectsNullInput()
    {
        Assert.Throws<ArgumentNullException>(() => EcdsaSignatureFormat.DerToRaw(null!));
    }

    // Helper: take a raw R||S signature and re-encode as DER for verification.
    private static byte[] ReEncodeRawAsDer(byte[] raw)
    {
        var r = new BigInteger(raw.AsSpan(0, 32), isUnsigned: true, isBigEndian: true);
        var s = new BigInteger(raw.AsSpan(32, 32), isUnsigned: true, isBigEndian: true);
        var writer = new AsnWriter(AsnEncodingRules.DER);
        using (writer.PushSequence())
        {
            writer.WriteInteger(r);
            writer.WriteInteger(s);
        }
        return writer.Encode();
    }
}
